"""empty message

Revision ID: 58a394659c5b
Revises: 3779a0092666
Create Date: 2025-05-07 13:52:09.354832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58a394659c5b'
down_revision = '3779a0092666'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_message_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_read_message_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('unread_count', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'friend_message', ['last_read_message_id'], ['id'])
        batch_op.create_foreign_key(None, 'friend_message', ['last_message_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('unread_count')
        batch_op.drop_column('last_read_message_id')
        batch_op.drop_column('last_message_id')

    # ### end Alembic commands ###
