"""empty message

Revision ID: 6e928a114950
Revises: 58a394659c5b
Create Date: 2025-05-11 16:38:38.938514

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6e928a114950'
down_revision = '58a394659c5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=50), nullable=True))
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', mysql.VARCHAR(collation='utf8_unicode_ci', length=50), nullable=True))
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###
